/* The dial-code list behind the site's phone fields: Arabic name, English name,
   dial code and ISO2 code (the `fi-xx` flag-icons suffix). Palestine leads —
   it is the default — then the Arab states, then the rest alphabetically by
   English name.

   The join modal's legacy dropdown builds itself from its own copy of this list
   inside `legacy-home.ts`; that file is a verbatim port of the legacy script, so
   it is left untouched rather than rewired to import from here. */
export type Country = {
  /** Arabic name */
  n: string;
  /** English name */
  e: string;
  /** dial code, e.g. "+970" */
  d: string;
  /** ISO2 code — the flag-icons class suffix */
  c: string;
};

export const COUNTRIES: Country[] = [
  { n: "فلسطين", e: "Palestine", d: "+970", c: "ps" },
  { n: "مصر", e: "Egypt", d: "+20", c: "eg" },
  { n: "الأردن", e: "Jordan", d: "+962", c: "jo" },
  { n: "السعودية", e: "Saudi Arabia", d: "+966", c: "sa" },
  { n: "الإمارات", e: "United Arab Emirates", d: "+971", c: "ae" },
  { n: "قطر", e: "Qatar", d: "+974", c: "qa" },
  { n: "الكويت", e: "Kuwait", d: "+965", c: "kw" },
  { n: "البحرين", e: "Bahrain", d: "+973", c: "bh" },
  { n: "عُمان", e: "Oman", d: "+968", c: "om" },
  { n: "اليمن", e: "Yemen", d: "+967", c: "ye" },
  { n: "العراق", e: "Iraq", d: "+964", c: "iq" },
  { n: "سوريا", e: "Syria", d: "+963", c: "sy" },
  { n: "لبنان", e: "Lebanon", d: "+961", c: "lb" },
  { n: "ليبيا", e: "Libya", d: "+218", c: "ly" },
  { n: "تونس", e: "Tunisia", d: "+216", c: "tn" },
  { n: "الجزائر", e: "Algeria", d: "+213", c: "dz" },
  { n: "المغرب", e: "Morocco", d: "+212", c: "ma" },
  { n: "السودان", e: "Sudan", d: "+249", c: "sd" },
  { n: "موريتانيا", e: "Mauritania", d: "+222", c: "mr" },
  { n: "الصومال", e: "Somalia", d: "+252", c: "so" },
  { n: "جيبوتي", e: "Djibouti", d: "+253", c: "dj" },
  { n: "جزر القمر", e: "Comoros", d: "+269", c: "km" },
  { n: "تركيا", e: "Turkey", d: "+90", c: "tr" },
  { n: "أفغانستان", e: "Afghanistan", d: "+93", c: "af" },
  { n: "ألبانيا", e: "Albania", d: "+355", c: "al" },
  { n: "أندورا", e: "Andorra", d: "+376", c: "ad" },
  { n: "أنغولا", e: "Angola", d: "+244", c: "ao" },
  { n: "أنتيغوا وباربودا", e: "Antigua and Barbuda", d: "+1268", c: "ag" },
  { n: "الأرجنتين", e: "Argentina", d: "+54", c: "ar" },
  { n: "أرمينيا", e: "Armenia", d: "+374", c: "am" },
  { n: "أستراليا", e: "Australia", d: "+61", c: "au" },
  { n: "النمسا", e: "Austria", d: "+43", c: "at" },
  { n: "أذربيجان", e: "Azerbaijan", d: "+994", c: "az" },
  { n: "الباهاما", e: "Bahamas", d: "+1242", c: "bs" },
  { n: "بنغلاديش", e: "Bangladesh", d: "+880", c: "bd" },
  { n: "بربادوس", e: "Barbados", d: "+1246", c: "bb" },
  { n: "بيلاروسيا", e: "Belarus", d: "+375", c: "by" },
  { n: "بلجيكا", e: "Belgium", d: "+32", c: "be" },
  { n: "بليز", e: "Belize", d: "+501", c: "bz" },
  { n: "بنين", e: "Benin", d: "+229", c: "bj" },
  { n: "بوتان", e: "Bhutan", d: "+975", c: "bt" },
  { n: "بوليفيا", e: "Bolivia", d: "+591", c: "bo" },
  { n: "البوسنة والهرسك", e: "Bosnia and Herzegovina", d: "+387", c: "ba" },
  { n: "بوتسوانا", e: "Botswana", d: "+267", c: "bw" },
  { n: "البرازيل", e: "Brazil", d: "+55", c: "br" },
  { n: "بروناي", e: "Brunei", d: "+673", c: "bn" },
  { n: "بلغاريا", e: "Bulgaria", d: "+359", c: "bg" },
  { n: "بوركينا فاسو", e: "Burkina Faso", d: "+226", c: "bf" },
  { n: "بوروندي", e: "Burundi", d: "+257", c: "bi" },
  { n: "كمبوديا", e: "Cambodia", d: "+855", c: "kh" },
  { n: "الكاميرون", e: "Cameroon", d: "+237", c: "cm" },
  { n: "كندا", e: "Canada", d: "+1", c: "ca" },
  { n: "الرأس الأخضر", e: "Cape Verde", d: "+238", c: "cv" },
  { n: "أفريقيا الوسطى", e: "Central African Republic", d: "+236", c: "cf" },
  { n: "تشاد", e: "Chad", d: "+235", c: "td" },
  { n: "تشيلي", e: "Chile", d: "+56", c: "cl" },
  { n: "الصين", e: "China", d: "+86", c: "cn" },
  { n: "كولومبيا", e: "Colombia", d: "+57", c: "co" },
  { n: "الكونغو الديمقراطية", e: "DR Congo", d: "+243", c: "cd" },
  { n: "الكونغو", e: "Congo", d: "+242", c: "cg" },
  { n: "كوستاريكا", e: "Costa Rica", d: "+506", c: "cr" },
  { n: "ساحل العاج", e: "Côte d'Ivoire", d: "+225", c: "ci" },
  { n: "كرواتيا", e: "Croatia", d: "+385", c: "hr" },
  { n: "كوبا", e: "Cuba", d: "+53", c: "cu" },
  { n: "قبرص", e: "Cyprus", d: "+357", c: "cy" },
  { n: "التشيك", e: "Czechia", d: "+420", c: "cz" },
  { n: "الدنمارك", e: "Denmark", d: "+45", c: "dk" },
  { n: "دومينيكا", e: "Dominica", d: "+1767", c: "dm" },
  { n: "جمهورية الدومينيكان", e: "Dominican Republic", d: "+1809", c: "do" },
  { n: "الإكوادور", e: "Ecuador", d: "+593", c: "ec" },
  { n: "السلفادور", e: "El Salvador", d: "+503", c: "sv" },
  { n: "غينيا الاستوائية", e: "Equatorial Guinea", d: "+240", c: "gq" },
  { n: "إريتريا", e: "Eritrea", d: "+291", c: "er" },
  { n: "إستونيا", e: "Estonia", d: "+372", c: "ee" },
  { n: "إسواتيني", e: "Eswatini", d: "+268", c: "sz" },
  { n: "إثيوبيا", e: "Ethiopia", d: "+251", c: "et" },
  { n: "فيجي", e: "Fiji", d: "+679", c: "fj" },
  { n: "فنلندا", e: "Finland", d: "+358", c: "fi" },
  { n: "فرنسا", e: "France", d: "+33", c: "fr" },
  { n: "الغابون", e: "Gabon", d: "+241", c: "ga" },
  { n: "غامبيا", e: "Gambia", d: "+220", c: "gm" },
  { n: "جورجيا", e: "Georgia", d: "+995", c: "ge" },
  { n: "ألمانيا", e: "Germany", d: "+49", c: "de" },
  { n: "غانا", e: "Ghana", d: "+233", c: "gh" },
  { n: "اليونان", e: "Greece", d: "+30", c: "gr" },
  { n: "غرينادا", e: "Grenada", d: "+1473", c: "gd" },
  { n: "غواتيمالا", e: "Guatemala", d: "+502", c: "gt" },
  { n: "غينيا", e: "Guinea", d: "+224", c: "gn" },
  { n: "غينيا بيساو", e: "Guinea-Bissau", d: "+245", c: "gw" },
  { n: "غيانا", e: "Guyana", d: "+592", c: "gy" },
  { n: "هايتي", e: "Haiti", d: "+509", c: "ht" },
  { n: "هندوراس", e: "Honduras", d: "+504", c: "hn" },
  { n: "المجر", e: "Hungary", d: "+36", c: "hu" },
  { n: "آيسلندا", e: "Iceland", d: "+354", c: "is" },
  { n: "الهند", e: "India", d: "+91", c: "in" },
  { n: "إندونيسيا", e: "Indonesia", d: "+62", c: "id" },
  { n: "إيران", e: "Iran", d: "+98", c: "ir" },
  { n: "أيرلندا", e: "Ireland", d: "+353", c: "ie" },
  { n: "إيطاليا", e: "Italy", d: "+39", c: "it" },
  { n: "جامايكا", e: "Jamaica", d: "+1876", c: "jm" },
  { n: "اليابان", e: "Japan", d: "+81", c: "jp" },
  { n: "كازاخستان", e: "Kazakhstan", d: "+7", c: "kz" },
  { n: "كينيا", e: "Kenya", d: "+254", c: "ke" },
  { n: "كيريباتي", e: "Kiribati", d: "+686", c: "ki" },
  { n: "كوريا الشمالية", e: "North Korea", d: "+850", c: "kp" },
  { n: "كوريا الجنوبية", e: "South Korea", d: "+82", c: "kr" },
  { n: "قيرغيزستان", e: "Kyrgyzstan", d: "+996", c: "kg" },
  { n: "لاوس", e: "Laos", d: "+856", c: "la" },
  { n: "لاتفيا", e: "Latvia", d: "+371", c: "lv" },
  { n: "ليسوتو", e: "Lesotho", d: "+266", c: "ls" },
  { n: "ليبيريا", e: "Liberia", d: "+231", c: "lr" },
  { n: "ليختنشتاين", e: "Liechtenstein", d: "+423", c: "li" },
  { n: "ليتوانيا", e: "Lithuania", d: "+370", c: "lt" },
  { n: "لوكسمبورغ", e: "Luxembourg", d: "+352", c: "lu" },
  { n: "مدغشقر", e: "Madagascar", d: "+261", c: "mg" },
  { n: "مالاوي", e: "Malawi", d: "+265", c: "mw" },
  { n: "ماليزيا", e: "Malaysia", d: "+60", c: "my" },
  { n: "المالديف", e: "Maldives", d: "+960", c: "mv" },
  { n: "مالي", e: "Mali", d: "+223", c: "ml" },
  { n: "مالطا", e: "Malta", d: "+356", c: "mt" },
  { n: "جزر مارشال", e: "Marshall Islands", d: "+692", c: "mh" },
  { n: "موريشيوس", e: "Mauritius", d: "+230", c: "mu" },
  { n: "المكسيك", e: "Mexico", d: "+52", c: "mx" },
  { n: "ميكرونيزيا", e: "Micronesia", d: "+691", c: "fm" },
  { n: "مولدوفا", e: "Moldova", d: "+373", c: "md" },
  { n: "موناكو", e: "Monaco", d: "+377", c: "mc" },
  { n: "منغوليا", e: "Mongolia", d: "+976", c: "mn" },
  { n: "الجبل الأسود", e: "Montenegro", d: "+382", c: "me" },
  { n: "موزمبيق", e: "Mozambique", d: "+258", c: "mz" },
  { n: "ميانمار", e: "Myanmar", d: "+95", c: "mm" },
  { n: "ناميبيا", e: "Namibia", d: "+264", c: "na" },
  { n: "ناورو", e: "Nauru", d: "+674", c: "nr" },
  { n: "نيبال", e: "Nepal", d: "+977", c: "np" },
  { n: "هولندا", e: "Netherlands", d: "+31", c: "nl" },
  { n: "نيوزيلندا", e: "New Zealand", d: "+64", c: "nz" },
  { n: "نيكاراغوا", e: "Nicaragua", d: "+505", c: "ni" },
  { n: "النيجر", e: "Niger", d: "+227", c: "ne" },
  { n: "نيجيريا", e: "Nigeria", d: "+234", c: "ng" },
  { n: "مقدونيا الشمالية", e: "North Macedonia", d: "+389", c: "mk" },
  { n: "النرويج", e: "Norway", d: "+47", c: "no" },
  { n: "باكستان", e: "Pakistan", d: "+92", c: "pk" },
  { n: "بالاو", e: "Palau", d: "+680", c: "pw" },
  { n: "بنما", e: "Panama", d: "+507", c: "pa" },
  { n: "بابوا غينيا الجديدة", e: "Papua New Guinea", d: "+675", c: "pg" },
  { n: "باراغواي", e: "Paraguay", d: "+595", c: "py" },
  { n: "بيرو", e: "Peru", d: "+51", c: "pe" },
  { n: "الفلبين", e: "Philippines", d: "+63", c: "ph" },
  { n: "بولندا", e: "Poland", d: "+48", c: "pl" },
  { n: "البرتغال", e: "Portugal", d: "+351", c: "pt" },
  { n: "رومانيا", e: "Romania", d: "+40", c: "ro" },
  { n: "روسيا", e: "Russia", d: "+7", c: "ru" },
  { n: "رواندا", e: "Rwanda", d: "+250", c: "rw" },
  { n: "سانت كيتس ونيفيس", e: "Saint Kitts and Nevis", d: "+1869", c: "kn" },
  { n: "سانت لوسيا", e: "Saint Lucia", d: "+1758", c: "lc" },
  { n: "سانت فينسنت والغرينادين", e: "Saint Vincent and the Grenadines", d: "+1784", c: "vc" },
  { n: "ساموا", e: "Samoa", d: "+685", c: "ws" },
  { n: "سان مارينو", e: "San Marino", d: "+378", c: "sm" },
  { n: "ساو تومي وبرينسيبي", e: "São Tomé and Príncipe", d: "+239", c: "st" },
  { n: "السنغال", e: "Senegal", d: "+221", c: "sn" },
  { n: "صربيا", e: "Serbia", d: "+381", c: "rs" },
  { n: "سيشل", e: "Seychelles", d: "+248", c: "sc" },
  { n: "سيراليون", e: "Sierra Leone", d: "+232", c: "sl" },
  { n: "سنغافورة", e: "Singapore", d: "+65", c: "sg" },
  { n: "سلوفاكيا", e: "Slovakia", d: "+421", c: "sk" },
  { n: "سلوفينيا", e: "Slovenia", d: "+386", c: "si" },
  { n: "جزر سليمان", e: "Solomon Islands", d: "+677", c: "sb" },
  { n: "جنوب أفريقيا", e: "South Africa", d: "+27", c: "za" },
  { n: "جنوب السودان", e: "South Sudan", d: "+211", c: "ss" },
  { n: "إسبانيا", e: "Spain", d: "+34", c: "es" },
  { n: "سريلانكا", e: "Sri Lanka", d: "+94", c: "lk" },
  { n: "سورينام", e: "Suriname", d: "+597", c: "sr" },
  { n: "السويد", e: "Sweden", d: "+46", c: "se" },
  { n: "سويسرا", e: "Switzerland", d: "+41", c: "ch" },
  { n: "تايوان", e: "Taiwan", d: "+886", c: "tw" },
  { n: "طاجيكستان", e: "Tajikistan", d: "+992", c: "tj" },
  { n: "تنزانيا", e: "Tanzania", d: "+255", c: "tz" },
  { n: "تايلاند", e: "Thailand", d: "+66", c: "th" },
  { n: "تيمور الشرقية", e: "Timor-Leste", d: "+670", c: "tl" },
  { n: "توغو", e: "Togo", d: "+228", c: "tg" },
  { n: "تونغا", e: "Tonga", d: "+676", c: "to" },
  { n: "ترينيداد وتوباغو", e: "Trinidad and Tobago", d: "+1868", c: "tt" },
  { n: "تركمانستان", e: "Turkmenistan", d: "+993", c: "tm" },
  { n: "توفالو", e: "Tuvalu", d: "+688", c: "tv" },
  { n: "أوغندا", e: "Uganda", d: "+256", c: "ug" },
  { n: "أوكرانيا", e: "Ukraine", d: "+380", c: "ua" },
  { n: "المملكة المتحدة", e: "United Kingdom", d: "+44", c: "gb" },
  { n: "الولايات المتحدة", e: "United States", d: "+1", c: "us" },
  { n: "أوروغواي", e: "Uruguay", d: "+598", c: "uy" },
  { n: "أوزبكستان", e: "Uzbekistan", d: "+998", c: "uz" },
  { n: "فانواتو", e: "Vanuatu", d: "+678", c: "vu" },
  { n: "الفاتيكان", e: "Vatican City", d: "+379", c: "va" },
  { n: "فنزويلا", e: "Venezuela", d: "+58", c: "ve" },
  { n: "فيتنام", e: "Vietnam", d: "+84", c: "vn" },
  { n: "زامبيا", e: "Zambia", d: "+260", c: "zm" },
  { n: "زيمبابوي", e: "Zimbabwe", d: "+263", c: "zw" },
];
