// @ts-nocheck
/* eslint-disable */

/* Partner companies shown in the "ابرز التعاونات" section. Selecting one swaps
   the reel poster, caption and testimonial. Extracted from CreatorCollaborations. */

export const VIDEO = "/assets/videos/WhatsApp Video 2026-03-23 at 11.59.11 AM.mp4";

export const COMPANIES = [
  {
    key: "creator_collab_c1",
    name: "شركة الإبداع للإنتاج",
    subKey: "creator_collab_c1_sub",
    sub: "إنتاج إعلامي",
    color: "#E1723B",
    poster: "/assets/images/1.png",
    titleKey: "creator_collab_c1_title",
    title: "أعلان لشركة الابداع",
    viewsKey: "creator_collab_c1_views",
    views: "200k مشاهدة",
    quoteKey: "creator_collab_c1_quote",
    quote:
      '"محمود يمتلك قدرة نادرة على تحويل الفكرة إلى تجربة بصرية مؤثرة. تعاوننا معه كان من أنجح تجاربنا الإنتاجية"',
    authorKey: "creator_collab_c1_author",
    author: "رنا الصالح",
    roleKey: "creator_collab_c1_role",
    role: "مدير الإنتاج",
    authorImg: "/assets/images/محمود زعيتر 2.png",
    stars: 4,
  },
  {
    key: "creator_collab_c2",
    name: "مؤسسة الفن العربي",
    subKey: "creator_collab_c2_sub",
    sub: "فنون وثقافة",
    color: "#6F7A4E",
    poster: "/assets/images/2.png",
    titleKey: "creator_collab_c2_title",
    title: "حملة الفن العربي",
    viewsKey: "creator_collab_c2_views",
    views: "150k مشاهدة",
    quoteKey: "creator_collab_c2_quote",
    quote:
      '"تعاملنا مع محمود كان تجربة فنية راقية، فهو يترجم رؤيتنا الثقافية إلى محتوى بصري يلامس الجمهور"',
    authorKey: "creator_collab_c2_author",
    author: "سامي العلي",
    roleKey: "creator_collab_c2_role",
    role: "مدير الإبداع",
    authorImg: "/assets/images/يوسف الدوس.png",
    stars: 5,
  },
  {
    key: "creator_collab_c3",
    name: "قناة الأفق الفضائية",
    subKey: "creator_collab_c3_sub",
    sub: "بث تلفزيوني",
    color: "#8BA86A",
    poster: "/assets/images/3.png",
    titleKey: "creator_collab_c3_title",
    title: "برومو قناة الأفق",
    viewsKey: "creator_collab_c3_views",
    views: "320k مشاهدة",
    quoteKey: "creator_collab_c3_quote",
    quote:
      '"احترافية عالية في التنفيذ والالتزام بالمواعيد. محمود أضاف لمسة مميزة على هويتنا الإعلامية"',
    authorKey: "creator_collab_c3_author",
    author: "هبة كمال",
    roleKey: "creator_collab_c3_role",
    role: "مديرة البرامج",
    authorImg: "/assets/images/مايك عوض 6.png",
    stars: 4,
  },
  {
    key: "creator_collab_c4",
    name: "دار النشر الحديثة",
    subKey: "creator_collab_c4_sub",
    sub: "نشر ومحتوى",
    color: "#4C5C37",
    poster: "/assets/images/4.png",
    titleKey: "creator_collab_c4_title",
    title: "حملة دار النشر",
    viewsKey: "creator_collab_c4_views",
    views: "90k مشاهدة",
    quoteKey: "creator_collab_c4_quote",
    quote:
      '"قدرته على صياغة المحتوى وربطه بالصورة جعلت مشاريعنا أكثر تأثيرًا ووصولًا لجمهور أوسع"',
    authorKey: "creator_collab_c4_author",
    author: "خالد منصور",
    roleKey: "creator_collab_c4_role",
    role: "مدير التحرير",
    authorImg: "/assets/images/yousef.png",
    stars: 5,
  },
  {
    key: "creator_collab_c5",
    name: "شركة تك ميديا",
    subKey: "creator_collab_c5_sub",
    sub: "تقنية إعلامية",
    color: "#5E7342",
    poster: "/assets/images/2.png",
    titleKey: "creator_collab_c5_title",
    title: "إعلان تك ميديا",
    viewsKey: "creator_collab_c5_views",
    views: "500k مشاهدة",
    quoteKey: "creator_collab_c5_quote",
    quote:
      '"دمج التقنية بالإبداع هو ما يميز عمل محمود، تعاوننا حقق أرقام مشاهدات تجاوزت توقعاتنا"',
    authorKey: "creator_collab_c5_author",
    author: "لينا فؤاد",
    roleKey: "creator_collab_c5_role",
    role: "مديرة التسويق",
    authorImg: "/assets/images/person.png",
    stars: 5,
  },
];
