"""Regenerate public/assets/vendor/fontawesome — the Font Awesome subset that
app/layout.tsx loads in place of the full cdnjs all.min.css.

Run it again after using an icon that is not in the subset yet:

    pip install fonttools brotli        # build tool only, not a site dependency
    python scripts/fa-subset.py

It downloads Font Awesome Free 6.2.1 (the version the site always used), keeps
every base / utility / animation / @font-face rule of all.min.css untouched,
drops the `.fa-NAME::before` rule of every icon that no file under src/ names,
and subsets the four fonts to the glyphs the kept rules point at (woff2 only).
"""
import os
import re
import subprocess
import sys
import tempfile
import urllib.request

VERSION = "6.2.1"
CDN = f"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/{VERSION}"
FONTS = ["fa-brands-400", "fa-regular-400", "fa-solid-900", "fa-v4compatibility"]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "public", "assets", "vendor", "fontawesome")


def used_icons() -> set[str]:
    names = set()
    for base, _, files in os.walk(os.path.join(ROOT, "src")):
        for name in files:
            if name.endswith((".ts", ".tsx", ".css")):
                with open(os.path.join(base, name), encoding="utf-8") as f:
                    names.update(re.findall(r"\bfa-([a-z0-9-]+)", f.read()))
    return names


def top_level_blocks(css: str) -> list[str]:
    blocks, depth, start = [], 0, 0
    for i, ch in enumerate(css):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                blocks.append(css[start : i + 1])
                start = i + 1
    return blocks


def main() -> None:
    used = used_icons()
    with urllib.request.urlopen(f"{CDN}/css/all.min.css") as r:
        css = r.read().decode("utf-8")
    licence = re.match(r"/\*!.*?\*/", css, flags=re.S).group(0)

    icon_selector = re.compile(r"^\.fa-([a-z0-9-]+):(?::)?(?:before|after)$")
    out, codepoints, kept = [], set(), set()
    for block in top_level_blocks(css[len(licence) :]):
        selector, body = block.split("{", 1)
        selectors = selector.split(",")
        matches = [icon_selector.match(s) for s in selectors]
        if selector.startswith("@") or not all(matches) or "content:" not in body:
            out.append(block)
            continue
        keep = [s for s, m in zip(selectors, matches) if m.group(1) in used]
        if not keep:
            continue
        kept.update(m.group(1) for m in matches if m.group(1) in used)
        for value in re.findall(r'content:"([^"]*)"', body):
            codepoints.update(int(h, 16) for h in re.findall(r"\x5c([0-9a-fA-F]+)", value))
        out.append(",".join(keep) + "{" + body)

    subset_css = "".join(out)
    subset_css = re.sub(r',url\(\.\./webfonts/[^)]+\.ttf\) format\("truetype"\)', "", subset_css)
    os.makedirs(os.path.join(OUT, "css"), exist_ok=True)
    os.makedirs(os.path.join(OUT, "webfonts"), exist_ok=True)
    with open(os.path.join(OUT, "css", "fa-subset.min.css"), "w", encoding="utf-8") as f:
        f.write(licence + "\n/* SUBSET of all.min.css — generated by scripts/fa-subset.py */\n" + subset_css)

    unicodes = ",".join(f"U+{c:04X}" for c in sorted(codepoints))
    with tempfile.TemporaryDirectory() as tmp:
        for font in FONTS:
            source = os.path.join(tmp, f"{font}.ttf")
            urllib.request.urlretrieve(f"{CDN}/webfonts/{font}.ttf", source)
            subprocess.run(
                [sys.executable, "-m", "fontTools.subset", source,
                 f"--unicodes={unicodes}", "--flavor=woff2", "--layout-features=*",
                 "--no-hinting", f"--output-file={os.path.join(OUT, 'webfonts', font + '.woff2')}"],
                check=True,
            )

    print(f"kept {len(kept)} icons, {len(codepoints)} glyphs")
    missing = sorted(used - kept - {"solid", "regular", "brands"})
    if missing:
        print(f"named in src/ but not icons in Font Awesome {VERSION}:", ", ".join(missing))


if __name__ == "__main__":
    main()
